import type { Style } from '@vue-pdf/stylesheet';

export const exactUtilities: Record<string, Style> = {
  flex: { display: 'flex' },
  hidden: { display: 'none' },
  inline: { display: 'flex' as const },
  block: { display: 'flex' as const },
  'flex-row': { flexDirection: 'row' },
  'flex-col': { flexDirection: 'column' },
  'flex-row-reverse': { flexDirection: 'row-reverse' },
  'flex-col-reverse': { flexDirection: 'column-reverse' },
  'flex-wrap': { flexWrap: 'wrap' },
  'flex-nowrap': { flexWrap: 'nowrap' as const },
  'flex-wrap-reverse': { flexWrap: 'wrap-reverse' },
  'flex-1': { flex: 1 },
  'flex-auto': { flex: 'auto' },
  'flex-initial': { flex: 'initial' },
  'flex-none': { flex: 'none' },
  grow: { flexGrow: 1 },
  'grow-0': { flexGrow: 0 },
  shrink: { flexShrink: 1 },
  'shrink-0': { flexShrink: 0 },
  absolute: { position: 'absolute' },
  relative: { position: 'relative' },
  static: { position: 'static' as const },

  'items-start': { alignItems: 'flex-start' },
  'items-end': { alignItems: 'flex-end' },
  'items-center': { alignItems: 'center' },
  'items-baseline': { alignItems: 'baseline' },
  'items-stretch': { alignItems: 'stretch' },

  'justify-start': { justifyContent: 'flex-start' },
  'justify-end': { justifyContent: 'flex-end' },
  'justify-center': { justifyContent: 'center' },
  'justify-between': { justifyContent: 'space-between' },
  'justify-around': { justifyContent: 'space-around' },
  'justify-evenly': { justifyContent: 'space-evenly' },

  'content-start': { alignContent: 'flex-start' },
  'content-end': { alignContent: 'flex-end' },
  'content-center': { alignContent: 'center' },
  'content-between': { alignContent: 'space-between' },
  'content-around': { alignContent: 'space-around' },

  'self-auto': { alignSelf: 'auto' },
  'self-start': { alignSelf: 'flex-start' },
  'self-end': { alignSelf: 'flex-end' },
  'self-center': { alignSelf: 'center' },
  'self-baseline': { alignSelf: 'baseline' },
  'self-stretch': { alignSelf: 'stretch' },

  italic: { fontStyle: 'italic' },
  'not-italic': { fontStyle: 'normal' },

  underline: { textDecoration: 'underline' },
  'line-through': { textDecoration: 'line-through' },
  'no-underline': { textDecoration: 'none' },

  uppercase: { textTransform: 'uppercase' },
  lowercase: { textTransform: 'lowercase' },
  capitalize: { textTransform: 'capitalize' },
  'normal-case': { textTransform: 'none' },

  'text-left': { textAlign: 'left' },
  'text-center': { textAlign: 'center' },
  'text-right': { textAlign: 'right' },
  'text-justify': { textAlign: 'justify' },

  border: { borderWidth: 1, borderStyle: 'solid' as const },
  'border-solid': { borderStyle: 'solid' },
  'border-dashed': { borderStyle: 'dashed' },
  'border-dotted': { borderStyle: 'dotted' },

  'overflow-hidden': { overflow: 'hidden' },

  'object-contain': { objectFit: 'contain' },
  'object-cover': { objectFit: 'cover' },
  'object-fill': { objectFit: 'fill' },
  'object-none': { objectFit: 'none' },
  'object-scale-down': { objectFit: 'scale-down' },

  'object-center': { objectPosition: 'center' },
  'object-top': { objectPosition: 'top' },
  'object-bottom': { objectPosition: 'bottom' },
  'object-left': { objectPosition: 'left' },
  'object-right': { objectPosition: 'right' },

  'w-auto': { width: 'auto' },
  'w-full': { width: '100%' },
  'w-screen': { width: '100vw' },
  'w-min': { width: 'min-content' },
  'w-max': { width: 'max-content' },
  'w-fit': { width: 'fit-content' },

  'h-auto': { height: 'auto' },
  'h-full': { height: '100%' },
  'h-screen': { height: '100vh' },
  'h-min': { height: 'min-content' },
  'h-max': { height: 'max-content' },
  'h-fit': { height: 'fit-content' },
};
